food/urls.py
from django.urls import path
from . import views


app_name = 'food'
urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('detail/<int:pk>/', views.Detail.as_view(), name='detail'),
    path('add/', views.Create_item.as_view(), name='create_item'),
    path('update/<int:id>/', views.update_item, name='update_item'),
    path('delete/<int:id>/', views.delete_item, name='delete_item')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profilepage, name='profilepage'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout')

]
urlpatterns += [

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.


class Item(models.Model):

    def __str__(self):
        return self.item_name

    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.ImageField(default='https://cdn.dribbble.com/users/1012566/screenshots/4187820/topic-2.jpg', upload_to='food_pictures')

    def get_absolute_url(self):
        return reverse('food:detail', kwargs={'pk': self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Profile(models.Model):

    def __str__(self):
        return self.user.username

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profile.jpg', upload_to='profile_pictures')
    location = models.CharField(max_length=200)

food/forms.py
from django import forms
from .models import Item


class ItemForm(forms.ModelForm):

    class Meta:
        model = Item
        fields = ['item_name', 'item_desc', 'item_price', 'item_image']

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

food/views.py
from django.shortcuts import render, redirect
from .models import Item
from django.template import loader
from .forms import ItemForm
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
# Create your views here.


def index(request):
    item_list = Item.objects.all()
    # template = loader.get_template('food/index.html')
    context = {
        'item_list': item_list,
    }
    return render(request, 'food/index.html', context)


class Index(ListView):
    model = Item
    template_name = 'food/index.html'
    context_object_name = 'item_list'


def detail(request, id):
    item = Item.objects.get(id=id)
    return render(request, 'food/detail.html', {'item': item})


class Detail(DetailView):
    model = Item
    template_name = 'food/detail.html'
    context_object_name = 'item'


def create_item(request):
    if request.method == 'POST':
        form = ItemForm(request.POST or None)
        if form.is_valid():
            form.save()
            return redirect('food:index')

    else:
        form = ItemForm()
    return render(request, 'food/item-form.html', {'form': form})


class Create_item(CreateView):
    model = Item
    fields = ['item_name', 'item_desc', 'item_price', 'item_image']
    template_name = 'food/item-form.html'

    def form_valid(self, form):
        form.instance.user_name = self.request.user
        return super().form_valid(form)


def update_item(request, id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST, instance=item)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request, 'food/item-form.html', {'form': form, 'item': item})


def delete_item(request, id):
    item = Item.objects.get(id=id)
    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    return render(request, 'food/delete-item.html', {'item': item})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from .forms import RegisterForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here.


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, 'Welcome {} your account is registered'.format(username))
            return redirect('login')
    else:
        form = RegisterForm()

    return render(request, 'users/register.html', {'form': form})


@login_required
def profilepage(request):
    return render(request, 'users/profile.html')

food/templates/food/base.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
  <link rel="stylesheet" href="{% static 'food.style.css'%}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
  <title>Document</title>
</head>
<body>
      <nav class="navbar navbar-dark bg-dark">
        <div class="navbar-brand">
          Food App
        </div>
        <div class="navbar">
          <a href="{% url  'food:create_item' %}" class="nav-item nav-link"> Add </a>
          <a href="#" class="nav-item nav-link"> Menu </a>
            {% if user.is_authenticated %}
                <a href="{% url 'profilepage' %}" class="nav-item nav-link"> Profile </a>
                <a href="{% url 'logout' %}" class="nav-item nav-link"> Logout </a>
            {% else %}
                <a href="{% url 'login' %}" class="nav-item nav-link"> Login </a>

            {% endif %}
        </div>
      </nav>
      {% if messages%}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
      {% endif %}
    {% block body %}
    {% endblock %}
</body>
</html>

food/templates/food/delete-item.html
<form method="POST">
  {% csrf_token %}
  <h1> Do You Want To Delete {{ item.item_name }}</h1>
  <button type="submit"> Confirm </button>

</form>

food/templates/food/detail.html
{% extends 'food/base.html' %}
{% block body %}
	<div class="container">
		<div class="row">
			<div class="col-md-6 ">
				<img src="{{ item.item_image.url }}" class="card" height="300px">
			</div>
			<div class="col-md-6">
				<h1>{{ item.item_name }}</h1>
				<h2>{{ item.item_desc }}</h2>
				<h3>$ {{ item.item_price }}</h3>
				<h2>{{ item.user_name }}</h2>

			</div>
			<div class="col-md-3">
				<a href="{% url 'food:update_item' item.id %}" class="btn btn-warning">
					UPDATE
				</a>
			</div>
		</div>
	</div>
{% endblock %}

food/templates/food/index.html
<!doctype html>
<html lang="en">
{% extends 'food/base.html' %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
       {% block body %}
        {% for item in item_list %}
           <div class="row">
               <div class="col-md-3 offset-md-2">
                   <img src="{{ item.item_image.url }}" class="card" height="150px">
               </div>
               <div class="col-md-4">
                   <h4>{{ item.item_name }}</h4>
                   <h5>{{ item.item_desc }}</h5>
                   <h6> ${{ item.item_price }}</h6>
                   <h4> {{ item.user_name }}</h4>

               </div>
               <div class="col-md-3">
                   <a href="{% url 'food:detail' item.id %}" class="btn btn-success"> Detail </a>
                   <a href="{% url 'food:delete_item' item.id %}" class="btn btn-success"> Delete </a>

               </div>
           </div>
        {% endfor %}
       {% endblock %}
</body>
</html>

food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}
		<div class="container">
			<div class="card">
				<div class="col-md-6 offset-md-2">
					<div class="card bg-info text-white">
						<div class="card-header">
							<b>ADD ITEM</b>
						</div>
					</div>
					<div class="card-body">
						<form method="POST">
							{% csrf_token %}
							{% for field in form%}
								<div class="form-group">
									{{ field.name }}
									{{ field }}
								</div>
							{% endfor %}
							<button type="submit">ADD</button>
						</form>

					</div>
				</div>
			</div>
		</div>
{% endblock %}

users/templates/users/login.html
{% extends 'food/base.html' %}
{% block body %}
  <div class="container">
    <div class="card">
      <div class="col-md-6 offset-md-2">
        <div class="card bg-info text-white">
          <div class="card-header">
            <b>LOGIN FORM</b>
          </div>
        </div>
        <div class="card-body">
          <form method="POST">
            {% csrf_token %}
            {% for field in form%}
            <div class="form-group">
              {{ field.name }}
              {{ field }}
            </div>
            {% endfor %}
            <button type="submit">LOGIN</button>
          </form>

        </div>
      </div>
    </div>
  </div>
{% endblock %}

users/templates/users/logout.html
<h1> YOU ARE LOGGED OUT </h1>

users/templates/users/profile.html
<h1>{{ user.username }}</h1>
<img src="{{ user.profile.image.url }}">

users/templates/users/register.html
{% extends 'food/base.html' %}
	{% block body %}
		<div class="container">
			<div class="card">
				<div class="col-md-6 offset-md-2">
					<div class="card bg-info text-white">
						<div class="card-header">
							<b>REGISTER FORM</b>
						</div>
					</div>
					<div class="card-body">
						<form method="POST">
							{% csrf_token %}
							{% for field in form%}
							<div class="form-group">
								{{ field.name }}
								{{ field }}
							</div>
							{% endfor %}
							<button type="submit">REGISTER</button>
						</form>

					</div>
				</div>
			</div>
		</div>
	{% endblock %}